// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgBidAuction } from "./types/carauction/carauction/tx";
import { MsgCancelBid } from "./types/carauction/carauction/tx";
import { MsgCreateAuction } from "./types/carauction/carauction/tx";

import { AuctionCreated as typeAuctionCreated} from "./types"
import { BidCreated as typeBidCreated} from "./types"
import { EndAuction as typeEndAuction} from "./types"
import { CancelBid as typeCancelBid} from "./types"
import { Params as typeParams} from "./types"
import { StoredAuction as typeStoredAuction} from "./types"
import { StoredBid as typeStoredBid} from "./types"
import { SystemInfo as typeSystemInfo} from "./types"

export { MsgBidAuction, MsgCancelBid, MsgCreateAuction };

type sendMsgBidAuctionParams = {
  value: MsgBidAuction,
  fee?: StdFee,
  memo?: string
};

type sendMsgCancelBidParams = {
  value: MsgCancelBid,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateAuctionParams = {
  value: MsgCreateAuction,
  fee?: StdFee,
  memo?: string
};


type msgBidAuctionParams = {
  value: MsgBidAuction,
};

type msgCancelBidParams = {
  value: MsgCancelBid,
};

type msgCreateAuctionParams = {
  value: MsgCreateAuction,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgBidAuction({ value, fee, memo }: sendMsgBidAuctionParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgBidAuction: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgBidAuction({ value: MsgBidAuction.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgBidAuction: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCancelBid({ value, fee, memo }: sendMsgCancelBidParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCancelBid: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCancelBid({ value: MsgCancelBid.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCancelBid: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateAuction({ value, fee, memo }: sendMsgCreateAuctionParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateAuction: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateAuction({ value: MsgCreateAuction.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateAuction: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgBidAuction({ value }: msgBidAuctionParams): EncodeObject {
			try {
				return { typeUrl: "/carauction.carauction.MsgBidAuction", value: MsgBidAuction.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgBidAuction: Could not create message: ' + e.message)
			}
		},
		
		msgCancelBid({ value }: msgCancelBidParams): EncodeObject {
			try {
				return { typeUrl: "/carauction.carauction.MsgCancelBid", value: MsgCancelBid.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCancelBid: Could not create message: ' + e.message)
			}
		},
		
		msgCreateAuction({ value }: msgCreateAuctionParams): EncodeObject {
			try {
				return { typeUrl: "/carauction.carauction.MsgCreateAuction", value: MsgCreateAuction.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateAuction: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						AuctionCreated: getStructure(typeAuctionCreated.fromPartial({})),
						BidCreated: getStructure(typeBidCreated.fromPartial({})),
						EndAuction: getStructure(typeEndAuction.fromPartial({})),
						CancelBid: getStructure(typeCancelBid.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						StoredAuction: getStructure(typeStoredAuction.fromPartial({})),
						StoredBid: getStructure(typeStoredBid.fromPartial({})),
						SystemInfo: getStructure(typeSystemInfo.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			CarauctionCarauction: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;